#开发环境配置
server:
  port: 8083


spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/db_bookmanage?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #访问templates下的html文件需要配置模板，映射
#  thymeleaf:
#    prefix:
#      classpath:/templates
#    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml



